class GSW_Berserk : Berserk replaces Berserk // Cheers, Tango!
{
	States
	{
		Spawn:
			PZRK A -1;
			Stop;
		Pickup:
			TNT1 A 0 {
				A_GiveInventory("GSW_PowerStrength");
				HealThing(100, 0);
				A_SetBlend("Red", .25, 35); // from Supercharge
			}
			Stop;
	}
}
class GSW_PowerStrength : PowerStrength replaces PowerStrength
{
	Default
	{
		Powerup.Duration 1;
		Powerup.Color "000000", 0.0;
		+INVENTORY.HUBPOWER
	}
}